auto: true

markdown: kramdown
kramdown:
    input: GFM
rouge: true
permalink: /:title

title: 格子
url: https://tantan0813.github.io/
feed: /atom.xml
author_info: <a href="https://tantan0813.github.io/">minTan</a>

