auto: true

markdown: kramdown
kramdown:
    input: GFM
rouge: true
permalink: /:title

title: 格子
url: https://tantan0813.github.io/
feed: /atom.xml
author_info: <a href="https://tantan0813.github.io/">minTan</a>

deploy:
  type: git
  repository: https://github.com/tantan0813/tantan0813.github.io.git
  branch: master

paginate: 5
paginate_path: "page:num"
gems: [jekyll-paginate]